config/routes.rb
Rails.application.routes.draw do
	root "users#index"
	resources :users
	resources :sessions
	resources :groups
	resources :meberships
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :meberships, dependent: :destroy

	validates :name, :description, presence: true
	validates :name, length: { minimum: 5 }
	validates :description, length: { minimum: 10 }
	
end

app/models/mebership.rb
class Mebership < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :groups
  has_many :meberships


  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :fname, :lname, :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	def require_login
    redirect_to '/sessions/new' if session[:user_id] == nil
  end

  def require_correct_user
    user = User.find(params[:id])
    redirect_to "/users/#{current_user.id}" if current_user != user
  end
  
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
	protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def index
		@user = User.find(session[:user_id]) 
		@groups = Group.all
	end

	def create
		data = group_params
		data['user'] = User.find(session[:user_id])
		group = Group.create(data)
		if group.errors.full_messages.length !=0 
			flash[:errors] = group.errors.full_messages
			redirect_to :back
		else
			Mebership.create(user:User.find(session[:user_id]),group:group)
			redirect_to :back
		end
	end

	def show
		@group = Group.find(params[:id])
		@members = @group.meberships.pluck(:user_id)
	end

	def destroy
		Group.find(params[:id]).delete
		redirect_to :back
	end

	private

	def group_params
		params.require(:group).permit(:name, :description)
	end
end

app/controllers/meberships_controller.rb
class MebershipsController < ApplicationController

	def create
		Mebership.create(user:User.find(session[:user_id]),group:Group.find(params[:id]))
		redirect_to :back
	end

	def destroy
		Mebership.where(user:session[:user_id],group:params[:id]).destroy_all
		redirect_to :back
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

		def create
		user = User.find_by(:email => user_params[:email])
		if user
			if  user.authenticate(user_params[:password])
				session[:user_id] = user.id 
				redirect_to groups_path
			else
				flash[:errors] = ["Invalid password"]
				redirect_to :back
			end
		else
			flash[:errors] = ["User not found"]
			redirect_to :back
		end 
	end 

	def destroy
		session.clear
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		user = User.create(user_params)
		if user.errors.full_messages.length !=0 
			flash[:errors] = user.errors.full_messages 
			redirect_to :back
		else 
			session[:user_id] = user.id
			redirect_to groups_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:fname, :lname,:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/meberships_helper.rb
module MebershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div id="header">
	<h1>Hi <%= @user.fname %> <%= @user.lname %>!</h1>
	<%= link_to 'Log Out', session_path("user_id"), :method => :delete %>
</div>

<div id="mid">
<div id="left">


<h2>Here are the organizations you may join:</h2>
<% if @groups%>
	<% @groups.each do |group|%>
			<p>
				<% if group.user.id == session[:user_id] %>
					<%= button_to 'X', group_path(:id => group.id), :method => :delete, :class => "x", :form_class => "x" %>
				<%end%>
				<a href="<%=group_path(group.id)%>">	<%= group.name%></a>
			</p>
			<p>Members: <%= group.meberships.count%></p>
			<p>Description: <%= group.description%></p>
	<%end%>
<%end%>
</div>

<div id="right">
<h1>Create a new organization</h1>
<form action='<%= groups_path %>' method='post'  >
	<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
	<label>Org Name: <input type="text" name="group[name]"></label>
	<label>Description: <textarea name="group[description]" ></textarea></label>
	<input class='green' type='submit' value='Submit'>
</form>
</div>
</div>

app/views/groups/show.html.erb
<div id="header">
<h1><%=@group.name%></h1>
	<a href="<%= groups_path %>">Dashboard</a>
	<%= link_to 'Log Out', session_path("user_id"), :method => :delete %>
</div>
	<div id="mid">

	

	<% if @members.include?(session[:user_id] ) %>
		<%= button_to 'Leave group', mebership_path(:id => @group.id), :method => :delete, :class => "green"  %>
		<% else %>
			<form action='<%= meberships_path %>' method='post'>
				<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
				<input type="hidden" name="id" value=<%=@group.id%>>
				<input class="green" type='submit' value='Join Group' >
			</form>
	<%end%>
	<p>Description: <%=@group.description%></p>

	<h1>Create by</h1>
		<% if @group.user.id == session[:user_id] %>
			<p>YOU</p>
		<% else %>
		<p><%=@group.user.fname%></p>
	<%end%>

	<h1>Members</h1>

	<% @group.meberships.each do |member|%>
		<p><%= member.user.fname%></p>
	<%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groups</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p><%= e %></p>
  <% end %>
<% end %>

<%= yield %>
</body>
</html>

app/views/users/index.html.erb
<div id="wrap">
	<div id="header">
		<h1 class="inline">Welcome!</h1>
	</div>
	<div id="mid">
		<div id="registration" class="box">
			<h1>Register</h1>

			<form action="<%= users_path %>" method="post">
				<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
				<label>First Name: <input type="text" name="user[fname]"></label>
				<label>Last Name: <input type="text" name="user[lname]"></label>
				<label>Email: <input type="email" name="user[email]"></label>
				<label>Password:<input type="password" name="user[password]"></label>
				<label><input class="green" type="submit" name="submit" value="Register"></label>
			</form>
		</div>
		
	<div id="login" class="box">
		<h1>Login</h1>
		<form action="<%= sessions_path %>" method="post">
			<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
			<label>Email: <input type="email" name="user[email]"></label>
			<label>Password:<input type="password" name="user[password]"></label>
			<label><input class="green"  type="submit" name="submit" value="Login"></label>
		</form>
	</div>

	</div>
</div>